version: '3'
services:
  node-app:
    build:
      context: .
      args:
        NODE_ENV: production
    environment:
      - NODE_ENV=production
    command: node index.js

# ----ORIGINAL-----
# version: '3'
# services:
#   node-app:
#     build:
#       context: .
#       args:
#         NODE_ENV: production
#     environment:
#       - NODE_ENV=production
#     command: node index.js
